export const QUESTIONS = [
{ country:'Alemania', code:'DE', tag:'Blitzkrieg', q:'¿Qué describe mejor el término "Blitzkrieg"?',
opts:['Ataques rápidos y combinados','Defensa estática fortificada','Campaña naval de portaaviones','Bombardeo sin apoyo terrestre'], a:0 },
{ country:'Alemania', code:'DE', tag:'Wehrmacht', q:'"Wehrmacht" se refiere a…',
opts:['Fuerza aérea','Fuerzas armadas de la Alemania nazi','Policía secreta','Resistencia alemana'], a:1 },
{ country:'Alemania', code:'DE', tag:'Barbarossa 1941', q:'¿Qué fue la Operación Barbarossa?',
opts:['Invasión de la URSS por Alemania','Desembarco en Normandía','Rendición alemana','Bombardeo de Londres'], a:0 },
{ country:'Alemania', code:'DE', tag:'Rudeltaktik', q:'La "Rudeltaktik" estaba asociada con…',
opts:['Panzer','U-Boot (submarinos)','Paracaidistas','Artillería'], a:1 },
{ country:'Alemania', code:'DE', tag:'Kristallnacht 1938', q:'La "Kristallnacht" fue…',
opts:['Ofensiva en Francia','Pogromo contra judíos en Alemania','Tratado con Italia','Huelga general'], a:1 },
{ country:'Italia', code:'IT', tag:'Pacto de Acero 1939', q:'¿Qué países firmaron el Pacto de Acero?',
opts:['Italia y Japón','Alemania e Italia','Alemania y Japón','Italia y España'], a:1 },
{ country:'Italia', code:'IT', tag:'Camicie Nere', q:'Las "Camicie Nere" eran…',
opts:['Unidad aérea','Milicia paramilitar fascista','Partido comunista','Resistencia'], a:1 },
{ country:'Italia', code:'IT', tag:'Cassibile 1943', q:'El Armisticio de Cassibile provocó…',
opts:['Entrada de Italia a la guerra','Rendición de Italia a los Aliados','Unión con Japón','Invasión de Etiopía'], a:1 },
{ country:'Japón', code:'JP', tag:'Pearl Harbor 1941', q:'¿Qué ocurrió el 7 de diciembre de 1941?',
opts:['Invasión alemana a la URSS','Ataque japonés a Pearl Harbor','Sicilia','Rendición japonesa'], a:1 },
{ country:'Japón', code:'JP', tag:'Kamikaze', q:'"Kamikaze" hace referencia a…',
opts:['Bombas terrestres','Pilotos suicidas','Submarinos miniatura','Espías'], a:1 },
{ country:'Japón', code:'JP', tag:'Bataan 1942', q:'La "Marcha de la Muerte de Bataan" ocurrió en…',
opts:['Filipinas','Malasia','China','Birmania'], a:0 },
{ country:'Japón', code:'JP', tag:'Hiroshima/Nagasaki 1945', q:'Los bombardeos atómicos de 1945 ocurrieron en…',
opts:['Tokio y Osaka','Hiroshima y Nagasaki','Seúl y Shanghái','Iwo Jima y Saipán'], a:1 },
{ country:'Japón', code:'JP', tag:'Wohlstandssphäre', q:'La "Gran Esfera de Coprosperidad" fue…',
opts:['Alianza igualitaria','Propaganda expansiva japonesa','Plan aliado','Conferencia de paz'], a:1 }
]